package gen

// Code generated by github.com/raphaelvigee/gensonschema. DO NOT EDIT!

import (
	"encoding/json"
	"strconv"

	"github.com/tidwall/gjson"
	"github.com/tidwall/sjson"
)

func pathJoin(p1, p2 string) string {
	if p1 == "" {
		return p2
	}

	return p1 + "." + p2
}

type __delegate interface {
	typeDefaultJson() []byte
}

type __node[D __delegate] struct {
	_json *[]byte
	_path string
}

func (r __node[D]) currentJson() []byte {
	if r._path == "" {
		return r.json()
	}

	res := r.result()
	return []byte(res.Raw)
}

func (r __node[D]) MarshalJSON() ([]byte, error) {
	return r.currentJson(), nil
}

func (r __node[D]) JSON() []byte {
	return r.currentJson()
}

func (r *__node[D]) UnmarshalJSON(b []byte) error {
	if r._json != nil {
		if r._path == "" {
			bcopy := make([]byte, len(b))
			copy(bcopy, b)

			r.setJson(bcopy)
			return nil
		}

		njson, err := sjson.SetRawBytes(r.json(), r.path(), b)
		if err != nil {
			return err
		}
		r.setJson(njson)
		return nil
	}

	bcopy := make([]byte, len(b))
	copy(bcopy, b)

	*r = __node[D]{_json: &bcopy}
	return nil
}

func (r __node[D]) json() []byte {
	if r._json == nil {
		return r.defaultJson()
	}

	return *r._json
}

func (r __node[D]) path() string {
	return r._path
}

func (r __node[D]) setJson(v []byte) {
	*r._json = v
}

func (r *__node[D]) ensureJson() {
	if r._json != nil {
		return
	}

	b := r.json()
	r._json = &b
}

func (r __node[D]) result() gjson.Result {
	if r._path == "" {
		return gjson.ParseBytes(r.json())
	}
	return gjson.GetBytes(r.json(), r.path())
}

func (r __node[D]) Exists() bool {
	return r.result().Exists()
}

func (r __node[D]) Delete() error {
	res, err := sjson.DeleteBytes(r.json(), r.path())
	if err != nil {
		return err
	}
	r.setJson(res)
	return nil
}

func (r *__node[D]) set(incoming []byte) error {
	r.ensureJson()

	if r._path == "" {
		r.setJson(incoming)
		return nil
	}

	res, err := sjson.SetRawBytes(r.json(), r.path(), incoming)
	if err != nil {
		return err
	}
	r.setJson(res)
	return nil
}

func (r *__node[D]) setArray(incoming []byte) error {
	param := []byte{'['}
	param = append(param, r.currentJson()...)
	param = append(param, ',')
	param = append(param, incoming...)
	param = append(param, ']')

	incoming = []byte(gjson.GetBytes(param, "@join").Raw)

	return r.set(incoming)
}

func (r __node[D]) copy() __node[D] {
	j := r.currentJson()
	b := make([]byte, len(j))
	copy(b, j)
	return __node[D]{
		_json: &b,
	}
}

func (r __node[D]) defaultJson() []byte {
	var d D
	return d.typeDefaultJson()
}

type AllOf struct {
	__node[AllOf]
}

func (r AllOf) Set(v *AllOf) error {
	incoming := v.currentJson()

	return r.set(incoming)
}

func (r *AllOf) GetBilling_address() *AllofDefinitionsAddress {
	r.ensureJson()
	return &AllofDefinitionsAddress{
		__node[AllofDefinitionsAddress]{
			_path: pathJoin(r._path, "billing_address"),
			_json: r._json,
		},
	}
}

func (r *AllOf) GetShipping_address() *AllofShipping_address {
	r.ensureJson()
	return &AllofShipping_address{
		__node[AllofShipping_address]{
			_path: pathJoin(r._path, "shipping_address"),
			_json: r._json,
		},
	}
}

func (r AllOf) Copy() *AllOf {
	return &AllOf{
		__node: r.copy(),
	}
}

func (r AllOf) typeDefaultJson() []byte {
	return []byte("{}")
}

type AllOfOneOf struct {
	__node[AllOfOneOf]
}

func (r AllOfOneOf) Set(v *AllOfOneOf) error {
	incoming := v.currentJson()

	return r.set(incoming)
}

func (r *AllOfOneOf) GetData() *AllofoneofData {
	r.ensureJson()
	return &AllofoneofData{
		__node[AllofoneofData]{
			_path: pathJoin(r._path, "data"),
			_json: r._json,
		},
	}
}

func (r AllOfOneOf) Copy() *AllOfOneOf {
	return &AllOfOneOf{
		__node: r.copy(),
	}
}

func (r AllOfOneOf) typeDefaultJson() []byte {
	return []byte("{}")
}

type AllofDefinitionsAddress struct {
	__node[AllofDefinitionsAddress]
}

func (r AllofDefinitionsAddress) Set(v *AllofDefinitionsAddress) error {
	incoming := v.currentJson()

	return r.set(incoming)
}

func (r *AllofDefinitionsAddress) GetCity() *String {
	r.ensureJson()
	return &String{
		__node[String]{
			_path: pathJoin(r._path, "city"),
			_json: r._json,
		},
	}
}

func (r AllofDefinitionsAddress) Copy() *AllofDefinitionsAddress {
	return &AllofDefinitionsAddress{
		__node: r.copy(),
	}
}

func (r AllofDefinitionsAddress) typeDefaultJson() []byte {
	return []byte("{}")
}

type AllofShipping_address struct {
	__node[AllofShipping_address]
}

func (r AllofShipping_address) Set(v *AllofShipping_address) error {
	incoming := v.currentJson()

	return r.setArray(incoming)
}

func (r *AllofShipping_address) GetCity() *String {
	r.ensureJson()
	return &String{
		__node[String]{
			_path: pathJoin(r._path, "city"),
			_json: r._json,
		},
	}
}

func (r *AllofShipping_address) GetType() *String {
	r.ensureJson()
	return &String{
		__node[String]{
			_path: pathJoin(r._path, "type"),
			_json: r._json,
		},
	}
}

func (r AllofShipping_address) Copy() *AllofShipping_address {
	return &AllofShipping_address{
		__node: r.copy(),
	}
}

func (r AllofShipping_address) typeDefaultJson() []byte {
	return []byte("{}")
}

type AllofoneofData struct {
	__node[AllofoneofData]
}

func (r AllofoneofData) Set(v *AllofoneofData) error {
	incoming := v.currentJson()

	return r.setArray(incoming)
}

func (r *AllofoneofData) AsAllOf0OneOf0() *AllofoneofDataAllOf0OneOf0 {
	r.ensureJson()
	return &AllofoneofDataAllOf0OneOf0{
		__node[AllofoneofDataAllOf0OneOf0]{
			_path: r._path,
			_json: r._json,
		},
	}
}

func (r *AllofoneofData) AsAllOf0OneOf1() *AllofoneofDataAllOf0OneOf1 {
	r.ensureJson()
	return &AllofoneofDataAllOf0OneOf1{
		__node[AllofoneofDataAllOf0OneOf1]{
			_path: r._path,
			_json: r._json,
		},
	}
}

func (r *AllofoneofData) AsAllOf3OneOf1() *AllofoneofDataAllOf3OneOf1 {
	r.ensureJson()
	return &AllofoneofDataAllOf3OneOf1{
		__node[AllofoneofDataAllOf3OneOf1]{
			_path: r._path,
			_json: r._json,
		},
	}
}

func (r *AllofoneofData) AsDNestedTitle1() *DNestedTitle1 {
	r.ensureJson()
	return &DNestedTitle1{
		__node[DNestedTitle1]{
			_path: r._path,
			_json: r._json,
		},
	}
}

func (r *AllofoneofData) AsNamedOneOf0() *AllofoneofDataAllOf2OneOf0 {
	r.ensureJson()
	return &AllofoneofDataAllOf2OneOf0{
		__node[AllofoneofDataAllOf2OneOf0]{
			_path: r._path,
			_json: r._json,
		},
	}
}

func (r *AllofoneofData) AsNamedOneOf1() *AllofoneofDataAllOf2OneOf1 {
	r.ensureJson()
	return &AllofoneofDataAllOf2OneOf1{
		__node[AllofoneofDataAllOf2OneOf1]{
			_path: r._path,
			_json: r._json,
		},
	}
}

func (r *AllofoneofData) GetB() *String {
	r.ensureJson()
	return &String{
		__node[String]{
			_path: pathJoin(r._path, "b"),
			_json: r._json,
		},
	}
}

func (r AllofoneofData) Copy() *AllofoneofData {
	return &AllofoneofData{
		__node: r.copy(),
	}
}

func (r AllofoneofData) typeDefaultJson() []byte {
	return []byte("{}")
}

type AllofoneofDataAllOf0OneOf0 struct {
	__node[AllofoneofDataAllOf0OneOf0]
}

func (r AllofoneofDataAllOf0OneOf0) Set(v *AllofoneofDataAllOf0OneOf0) error {
	incoming := v.currentJson()

	return r.set(incoming)
}

func (r *AllofoneofDataAllOf0OneOf0) GetA1() *String {
	r.ensureJson()
	return &String{
		__node[String]{
			_path: pathJoin(r._path, "a1"),
			_json: r._json,
		},
	}
}

func (r AllofoneofDataAllOf0OneOf0) Copy() *AllofoneofDataAllOf0OneOf0 {
	return &AllofoneofDataAllOf0OneOf0{
		__node: r.copy(),
	}
}

func (r AllofoneofDataAllOf0OneOf0) typeDefaultJson() []byte {
	return []byte("{}")
}

type AllofoneofDataAllOf0OneOf1 struct {
	__node[AllofoneofDataAllOf0OneOf1]
}

func (r AllofoneofDataAllOf0OneOf1) Set(v *AllofoneofDataAllOf0OneOf1) error {
	incoming := v.currentJson()

	return r.set(incoming)
}

func (r *AllofoneofDataAllOf0OneOf1) GetA2() *String {
	r.ensureJson()
	return &String{
		__node[String]{
			_path: pathJoin(r._path, "a2"),
			_json: r._json,
		},
	}
}

func (r AllofoneofDataAllOf0OneOf1) Copy() *AllofoneofDataAllOf0OneOf1 {
	return &AllofoneofDataAllOf0OneOf1{
		__node: r.copy(),
	}
}

func (r AllofoneofDataAllOf0OneOf1) typeDefaultJson() []byte {
	return []byte("{}")
}

type AllofoneofDataAllOf2OneOf0 struct {
	__node[AllofoneofDataAllOf2OneOf0]
}

func (r AllofoneofDataAllOf2OneOf0) Set(v *AllofoneofDataAllOf2OneOf0) error {
	incoming := v.currentJson()

	return r.set(incoming)
}

func (r *AllofoneofDataAllOf2OneOf0) GetC1() *String {
	r.ensureJson()
	return &String{
		__node[String]{
			_path: pathJoin(r._path, "c1"),
			_json: r._json,
		},
	}
}

func (r AllofoneofDataAllOf2OneOf0) Copy() *AllofoneofDataAllOf2OneOf0 {
	return &AllofoneofDataAllOf2OneOf0{
		__node: r.copy(),
	}
}

func (r AllofoneofDataAllOf2OneOf0) typeDefaultJson() []byte {
	return []byte("{}")
}

type AllofoneofDataAllOf2OneOf1 struct {
	__node[AllofoneofDataAllOf2OneOf1]
}

func (r AllofoneofDataAllOf2OneOf1) Set(v *AllofoneofDataAllOf2OneOf1) error {
	incoming := v.currentJson()

	return r.set(incoming)
}

func (r *AllofoneofDataAllOf2OneOf1) GetC2() *String {
	r.ensureJson()
	return &String{
		__node[String]{
			_path: pathJoin(r._path, "c2"),
			_json: r._json,
		},
	}
}

func (r AllofoneofDataAllOf2OneOf1) Copy() *AllofoneofDataAllOf2OneOf1 {
	return &AllofoneofDataAllOf2OneOf1{
		__node: r.copy(),
	}
}

func (r AllofoneofDataAllOf2OneOf1) typeDefaultJson() []byte {
	return []byte("{}")
}

type AllofoneofDataAllOf3OneOf1 struct {
	__node[AllofoneofDataAllOf3OneOf1]
}

func (r AllofoneofDataAllOf3OneOf1) Set(v *AllofoneofDataAllOf3OneOf1) error {
	incoming := v.currentJson()

	return r.set(incoming)
}

func (r *AllofoneofDataAllOf3OneOf1) GetD2() *String {
	r.ensureJson()
	return &String{
		__node[String]{
			_path: pathJoin(r._path, "d2"),
			_json: r._json,
		},
	}
}

func (r AllofoneofDataAllOf3OneOf1) Copy() *AllofoneofDataAllOf3OneOf1 {
	return &AllofoneofDataAllOf3OneOf1{
		__node: r.copy(),
	}
}

func (r AllofoneofDataAllOf3OneOf1) typeDefaultJson() []byte {
	return []byte("{}")
}

type ArrayArray struct {
	__node[ArrayArray]
}

func (r ArrayArray) Set(v *ArrayArray) error {
	incoming := v.currentJson()

	return r.set(incoming)
}

func (r *ArrayArray) GetTopfield1() *ArrayTopfield1 {
	r.ensureJson()
	return &ArrayTopfield1{
		__node[ArrayTopfield1]{
			_path: pathJoin(r._path, "topfield1"),
			_json: r._json,
		},
	}
}

func (r *ArrayArray) GetTopfield2() *ArrayTopfield2 {
	r.ensureJson()
	return &ArrayTopfield2{
		__node[ArrayTopfield2]{
			_path: pathJoin(r._path, "topfield2"),
			_json: r._json,
		},
	}
}

func (r ArrayArray) Copy() *ArrayArray {
	return &ArrayArray{
		__node: r.copy(),
	}
}

func (r ArrayArray) typeDefaultJson() []byte {
	return []byte("{}")
}

type ArrayDefinitionsDef1 struct {
	__node[ArrayDefinitionsDef1]
}

func (r ArrayDefinitionsDef1) Set(v *ArrayDefinitionsDef1) error {
	incoming := v.currentJson()

	return r.set(incoming)
}

func (r *ArrayDefinitionsDef1) GetField1() *String {
	r.ensureJson()
	return &String{
		__node[String]{
			_path: pathJoin(r._path, "field1"),
			_json: r._json,
		},
	}
}

func (r *ArrayDefinitionsDef1) GetField2() *String {
	r.ensureJson()
	return &String{
		__node[String]{
			_path: pathJoin(r._path, "field2"),
			_json: r._json,
		},
	}
}

func (r ArrayDefinitionsDef1) Copy() *ArrayDefinitionsDef1 {
	return &ArrayDefinitionsDef1{
		__node: r.copy(),
	}
}

func (r ArrayDefinitionsDef1) typeDefaultJson() []byte {
	return []byte("{}")
}

type ArrayTopfield1 struct {
	__node[ArrayTopfield1]
}

func (r ArrayTopfield1) Set(v *ArrayTopfield1) error {
	incoming := v.currentJson()

	return r.set(incoming)
}

func (r *ArrayTopfield1) Append(v *ArrayDefinitionsDef1) error {
	r.ensureJson()
	return r.At(-1).Set(v)
}

func (r *ArrayTopfield1) At(i int) *ArrayDefinitionsDef1 {
	r.ensureJson()
	return &ArrayDefinitionsDef1{
		__node[ArrayDefinitionsDef1]{
			_path: pathJoin(r._path, strconv.Itoa(i)),
			_json: r._json,
		},
	}
}

func (r ArrayTopfield1) Clear() error {
	return r.set([]byte("[]"))
}

func (r ArrayTopfield1) Len() int {
	res := r.result()
	if !res.IsArray() {
		return 0
	}
	return int(res.Get("#").Int())
}

func (r ArrayTopfield1) Copy() *ArrayTopfield1 {
	return &ArrayTopfield1{
		__node: r.copy(),
	}
}

func (r ArrayTopfield1) typeDefaultJson() []byte {
	return []byte("[]")
}

type ArrayTopfield2 struct {
	__node[ArrayTopfield2]
}

func (r ArrayTopfield2) Value() []string {
	res := r.result()
	var v []string
	_ = json.Unmarshal([]byte(res.Raw), &v)
	return v
}
func (r *ArrayTopfield2) Append(v string) error {
	r.ensureJson()
	return r.At(-1).Set(v)
}

func (r *ArrayTopfield2) At(i int) *String {
	r.ensureJson()
	return &String{
		__node[String]{
			_path: pathJoin(r._path, strconv.Itoa(i)),
			_json: r._json,
		},
	}
}

func (r *ArrayTopfield2) Set(v []string) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	return r.set(b)
}

func (r ArrayTopfield2) Clear() error {
	return r.set([]byte("[]"))
}

func (r ArrayTopfield2) Len() int {
	res := r.result()
	if !res.IsArray() {
		return 0
	}
	return int(res.Get("#").Int())
}

func (r ArrayTopfield2) Copy() *ArrayTopfield2 {
	return &ArrayTopfield2{
		__node: r.copy(),
	}
}

func (r ArrayTopfield2) typeDefaultJson() []byte {
	return []byte("[]")
}

type ArraysSchemaArraysSchema struct {
	__node[ArraysSchemaArraysSchema]
}

func (r ArraysSchemaArraysSchema) Set(v *ArraysSchemaArraysSchema) error {
	incoming := v.currentJson()

	return r.set(incoming)
}

func (r *ArraysSchemaArraysSchema) GetFruits() *ArraysSchemaFruits {
	r.ensureJson()
	return &ArraysSchemaFruits{
		__node[ArraysSchemaFruits]{
			_path: pathJoin(r._path, "fruits"),
			_json: r._json,
		},
	}
}

func (r *ArraysSchemaArraysSchema) GetVegetables() *ArraysSchemaVegetables {
	r.ensureJson()
	return &ArraysSchemaVegetables{
		__node[ArraysSchemaVegetables]{
			_path: pathJoin(r._path, "vegetables"),
			_json: r._json,
		},
	}
}

func (r ArraysSchemaArraysSchema) Copy() *ArraysSchemaArraysSchema {
	return &ArraysSchemaArraysSchema{
		__node: r.copy(),
	}
}

func (r ArraysSchemaArraysSchema) typeDefaultJson() []byte {
	return []byte("{}")
}

type ArraysSchemaDefsVeggie struct {
	__node[ArraysSchemaDefsVeggie]
}

func (r ArraysSchemaDefsVeggie) Set(v *ArraysSchemaDefsVeggie) error {
	incoming := v.currentJson()

	return r.set(incoming)
}

func (r *ArraysSchemaDefsVeggie) GetVeggieLike() *Bool {
	r.ensureJson()
	return &Bool{
		__node[Bool]{
			_path: pathJoin(r._path, "veggieLike"),
			_json: r._json,
		},
	}
}

func (r *ArraysSchemaDefsVeggie) GetVeggieName() *String {
	r.ensureJson()
	return &String{
		__node[String]{
			_path: pathJoin(r._path, "veggieName"),
			_json: r._json,
		},
	}
}

func (r ArraysSchemaDefsVeggie) Copy() *ArraysSchemaDefsVeggie {
	return &ArraysSchemaDefsVeggie{
		__node: r.copy(),
	}
}

func (r ArraysSchemaDefsVeggie) typeDefaultJson() []byte {
	return []byte("{}")
}

type ArraysSchemaFruits struct {
	__node[ArraysSchemaFruits]
}

func (r ArraysSchemaFruits) Value() []string {
	res := r.result()
	var v []string
	_ = json.Unmarshal([]byte(res.Raw), &v)
	return v
}
func (r *ArraysSchemaFruits) Append(v string) error {
	r.ensureJson()
	return r.At(-1).Set(v)
}

func (r *ArraysSchemaFruits) At(i int) *String {
	r.ensureJson()
	return &String{
		__node[String]{
			_path: pathJoin(r._path, strconv.Itoa(i)),
			_json: r._json,
		},
	}
}

func (r *ArraysSchemaFruits) Set(v []string) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	return r.set(b)
}

func (r ArraysSchemaFruits) Clear() error {
	return r.set([]byte("[]"))
}

func (r ArraysSchemaFruits) Len() int {
	res := r.result()
	if !res.IsArray() {
		return 0
	}
	return int(res.Get("#").Int())
}

func (r ArraysSchemaFruits) Copy() *ArraysSchemaFruits {
	return &ArraysSchemaFruits{
		__node: r.copy(),
	}
}

func (r ArraysSchemaFruits) typeDefaultJson() []byte {
	return []byte("[]")
}

type ArraysSchemaVegetables struct {
	__node[ArraysSchemaVegetables]
}

func (r ArraysSchemaVegetables) Set(v *ArraysSchemaVegetables) error {
	incoming := v.currentJson()

	return r.set(incoming)
}

func (r *ArraysSchemaVegetables) Append(v *ArraysSchemaDefsVeggie) error {
	r.ensureJson()
	return r.At(-1).Set(v)
}

func (r *ArraysSchemaVegetables) At(i int) *ArraysSchemaDefsVeggie {
	r.ensureJson()
	return &ArraysSchemaDefsVeggie{
		__node[ArraysSchemaDefsVeggie]{
			_path: pathJoin(r._path, strconv.Itoa(i)),
			_json: r._json,
		},
	}
}

func (r ArraysSchemaVegetables) Clear() error {
	return r.set([]byte("[]"))
}

func (r ArraysSchemaVegetables) Len() int {
	res := r.result()
	if !res.IsArray() {
		return 0
	}
	return int(res.Get("#").Int())
}

func (r ArraysSchemaVegetables) Copy() *ArraysSchemaVegetables {
	return &ArraysSchemaVegetables{
		__node: r.copy(),
	}
}

func (r ArraysSchemaVegetables) typeDefaultJson() []byte {
	return []byte("[]")
}

type Bool struct {
	__node[Bool]
}

func (r Bool) Value() bool {
	res := r.result()
	return res.Bool()
}
func (r *Bool) Set(v bool) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	return r.set(b)
}

func (r Bool) Copy() *Bool {
	return &Bool{
		__node: r.copy(),
	}
}

func (r Bool) typeDefaultJson() []byte {
	return []byte("")
}

type DNestedTitle1 struct {
	__node[DNestedTitle1]
}

func (r DNestedTitle1) Set(v *DNestedTitle1) error {
	incoming := v.currentJson()

	return r.set(incoming)
}

func (r *DNestedTitle1) GetD1() *String {
	r.ensureJson()
	return &String{
		__node[String]{
			_path: pathJoin(r._path, "d1"),
			_json: r._json,
		},
	}
}

func (r DNestedTitle1) Copy() *DNestedTitle1 {
	return &DNestedTitle1{
		__node: r.copy(),
	}
}

func (r DNestedTitle1) typeDefaultJson() []byte {
	return []byte("{}")
}

type Int64 struct {
	__node[Int64]
}

func (r Int64) Value() int64 {
	res := r.result()
	return res.Int()
}
func (r *Int64) Set(v int64) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	return r.set(b)
}

func (r Int64) Copy() *Int64 {
	return &Int64{
		__node: r.copy(),
	}
}

func (r Int64) typeDefaultJson() []byte {
	return []byte("")
}

type NestedarraysField1 struct {
	__node[NestedarraysField1]
}

func (r NestedarraysField1) Set(v *NestedarraysField1) error {
	incoming := v.currentJson()

	return r.set(incoming)
}

func (r *NestedarraysField1) Append(v *NestedarraysField1Items) error {
	r.ensureJson()
	return r.At(-1).Set(v)
}

func (r *NestedarraysField1) At(i int) *NestedarraysField1Items {
	r.ensureJson()
	return &NestedarraysField1Items{
		__node[NestedarraysField1Items]{
			_path: pathJoin(r._path, strconv.Itoa(i)),
			_json: r._json,
		},
	}
}

func (r NestedarraysField1) Clear() error {
	return r.set([]byte("[]"))
}

func (r NestedarraysField1) Len() int {
	res := r.result()
	if !res.IsArray() {
		return 0
	}
	return int(res.Get("#").Int())
}

func (r NestedarraysField1) Copy() *NestedarraysField1 {
	return &NestedarraysField1{
		__node: r.copy(),
	}
}

func (r NestedarraysField1) typeDefaultJson() []byte {
	return []byte("[]")
}

type NestedarraysField1Items struct {
	__node[NestedarraysField1Items]
}

func (r NestedarraysField1Items) Set(v *NestedarraysField1Items) error {
	incoming := v.currentJson()

	return r.set(incoming)
}

func (r *NestedarraysField1Items) GetField2() *NestedarraysField1ItemsField2 {
	r.ensureJson()
	return &NestedarraysField1ItemsField2{
		__node[NestedarraysField1ItemsField2]{
			_path: pathJoin(r._path, "field2"),
			_json: r._json,
		},
	}
}

func (r NestedarraysField1Items) Copy() *NestedarraysField1Items {
	return &NestedarraysField1Items{
		__node: r.copy(),
	}
}

func (r NestedarraysField1Items) typeDefaultJson() []byte {
	return []byte("{}")
}

type NestedarraysField1ItemsField2 struct {
	__node[NestedarraysField1ItemsField2]
}

func (r NestedarraysField1ItemsField2) Set(v *NestedarraysField1ItemsField2) error {
	incoming := v.currentJson()

	return r.set(incoming)
}

func (r *NestedarraysField1ItemsField2) Append(v *SomeTitle) error {
	r.ensureJson()
	return r.At(-1).Set(v)
}

func (r *NestedarraysField1ItemsField2) At(i int) *SomeTitle {
	r.ensureJson()
	return &SomeTitle{
		__node[SomeTitle]{
			_path: pathJoin(r._path, strconv.Itoa(i)),
			_json: r._json,
		},
	}
}

func (r NestedarraysField1ItemsField2) Clear() error {
	return r.set([]byte("[]"))
}

func (r NestedarraysField1ItemsField2) Len() int {
	res := r.result()
	if !res.IsArray() {
		return 0
	}
	return int(res.Get("#").Int())
}

func (r NestedarraysField1ItemsField2) Copy() *NestedarraysField1ItemsField2 {
	return &NestedarraysField1ItemsField2{
		__node: r.copy(),
	}
}

func (r NestedarraysField1ItemsField2) typeDefaultJson() []byte {
	return []byte("[]")
}

type NestedarraysNestedarrays struct {
	__node[NestedarraysNestedarrays]
}

func (r NestedarraysNestedarrays) Set(v *NestedarraysNestedarrays) error {
	incoming := v.currentJson()

	return r.set(incoming)
}

func (r *NestedarraysNestedarrays) GetField1() *NestedarraysField1 {
	r.ensureJson()
	return &NestedarraysField1{
		__node[NestedarraysField1]{
			_path: pathJoin(r._path, "field1"),
			_json: r._json,
		},
	}
}

func (r NestedarraysNestedarrays) Copy() *NestedarraysNestedarrays {
	return &NestedarraysNestedarrays{
		__node: r.copy(),
	}
}

func (r NestedarraysNestedarrays) typeDefaultJson() []byte {
	return []byte("{}")
}

type OneOf struct {
	__node[OneOf]
}

func (r OneOf) Set(v *OneOf) error {
	incoming := v.currentJson()

	return r.set(incoming)
}

func (r *OneOf) GetData() *OneofData {
	r.ensureJson()
	return &OneofData{
		__node[OneofData]{
			_path: pathJoin(r._path, "data"),
			_json: r._json,
		},
	}
}

func (r OneOf) Copy() *OneOf {
	return &OneOf{
		__node: r.copy(),
	}
}

func (r OneOf) typeDefaultJson() []byte {
	return []byte("{}")
}

type OneOfRootObj struct {
	__node[OneOfRootObj]
}

func (r OneOfRootObj) Set(v *OneOfRootObj) error {
	incoming := v.currentJson()

	return r.set(incoming)
}

func (r *OneOfRootObj) AsPerson() *Person {
	r.ensureJson()
	return &Person{
		__node[Person]{
			_path: r._path,
			_json: r._json,
		},
	}
}

func (r *OneOfRootObj) AsVehicle() *Vehicle {
	r.ensureJson()
	return &Vehicle{
		__node[Vehicle]{
			_path: r._path,
			_json: r._json,
		},
	}
}

func (r OneOfRootObj) Copy() *OneOfRootObj {
	return &OneOfRootObj{
		__node: r.copy(),
	}
}

func (r OneOfRootObj) typeDefaultJson() []byte {
	return []byte("{}")
}

type OneofData struct {
	__node[OneofData]
}

func (r OneofData) Set(v *OneofData) error {
	incoming := v.currentJson()

	return r.set(incoming)
}

func (r *OneofData) AsPerson() *Person {
	r.ensureJson()
	return &Person{
		__node[Person]{
			_path: r._path,
			_json: r._json,
		},
	}
}

func (r *OneofData) AsVehicle() *Vehicle {
	r.ensureJson()
	return &Vehicle{
		__node[Vehicle]{
			_path: r._path,
			_json: r._json,
		},
	}
}

func (r OneofData) Copy() *OneofData {
	return &OneofData{
		__node: r.copy(),
	}
}

func (r OneofData) typeDefaultJson() []byte {
	return []byte("{}")
}

type Person struct {
	__node[Person]
}

func (r Person) Set(v *Person) error {
	incoming := v.currentJson()

	return r.set(incoming)
}

func (r *Person) GetFirstName() *String {
	r.ensureJson()
	return &String{
		__node[String]{
			_path: pathJoin(r._path, "firstName"),
			_json: r._json,
		},
	}
}

func (r *Person) GetLastName() *String {
	r.ensureJson()
	return &String{
		__node[String]{
			_path: pathJoin(r._path, "lastName"),
			_json: r._json,
		},
	}
}

func (r *Person) GetSport() *String {
	r.ensureJson()
	return &String{
		__node[String]{
			_path: pathJoin(r._path, "sport"),
			_json: r._json,
		},
	}
}

func (r Person) Copy() *Person {
	return &Person{
		__node: r.copy(),
	}
}

func (r Person) typeDefaultJson() []byte {
	return []byte("{}")
}

type SomeTitle struct {
	__node[SomeTitle]
}

func (r SomeTitle) Set(v *SomeTitle) error {
	incoming := v.currentJson()

	return r.set(incoming)
}

func (r *SomeTitle) GetField3() *String {
	r.ensureJson()
	return &String{
		__node[String]{
			_path: pathJoin(r._path, "field3"),
			_json: r._json,
		},
	}
}

func (r SomeTitle) Copy() *SomeTitle {
	return &SomeTitle{
		__node: r.copy(),
	}
}

func (r SomeTitle) typeDefaultJson() []byte {
	return []byte("{}")
}

type String struct {
	__node[String]
}

func (r String) Value() string {
	res := r.result()
	return res.String()
}
func (r *String) Set(v string) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	return r.set(b)
}

func (r String) Copy() *String {
	return &String{
		__node: r.copy(),
	}
}

func (r String) typeDefaultJson() []byte {
	return []byte("")
}

type Vehicle struct {
	__node[Vehicle]
}

func (r Vehicle) Set(v *Vehicle) error {
	incoming := v.currentJson()

	return r.set(incoming)
}

func (r *Vehicle) GetBrand() *String {
	r.ensureJson()
	return &String{
		__node[String]{
			_path: pathJoin(r._path, "brand"),
			_json: r._json,
		},
	}
}

func (r *Vehicle) GetPrice() *Int64 {
	r.ensureJson()
	return &Int64{
		__node[Int64]{
			_path: pathJoin(r._path, "price"),
			_json: r._json,
		},
	}
}

func (r Vehicle) Copy() *Vehicle {
	return &Vehicle{
		__node: r.copy(),
	}
}

func (r Vehicle) typeDefaultJson() []byte {
	return []byte("{}")
}
